{{- if and (contains "secure" .Values.apps) (.Values.sysdig.secure.apiDocs.enabled) }}
{{- if and (eq .Values.deployment "iks") (ne .Values.sysdig.ingressNetworking "external") -}}
{{- if and (.Values.sysdig.iks.nginxIngressEnabled) (.Values.sysdig.iks.privateAPIDNSName) -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sysdigcloud-api-docs-private
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: private-iks-k8s-nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "True"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Private-Endpoint true;
spec:
  rules:
  - host: {{ .Values.sysdig.iks.privateAPIDNSName }}
    http:
      paths:
        - backend:
            serviceName: sysdigcloud-api-docs
            servicePort: 80
          path: /api/docs/secure
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.sysdig.iks.privateAPIDNSName }}
      secretName: sysdigcloud-ssl-secret
{{- end -}}
{{- end }}
{{- end }}
