openapi: 3.0.0

info:
  title: Reporting Secure Internal API
  description: Internal API for Reporting service in Sysdig Secure
  version: "v1"

paths:
  /api/reporting/v1/{domain}/schedules/disable:
    post:
      summary: Disable schedules
      description: Disable multiple schedules for report generation at once.
      tags:
        - Reporting
      parameters:
        - $ref: "#/components/parameters/domain"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schedules:
                  type: array
                  description: >-
                    Array of all the schedule IDs for report generation which need to be disabled
                  items:
                    type: string
                    example: schedule-1hDkklCWc5UtuFhwCaZkbFNY5ZV
      responses:
        "200":
          description: The list of all disabled schedules for report generation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ReportSchedule"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportingError"
              example: "Invalid report configuration"

components:
  parameters:
    domain:
      in: path
      name: domain
      schema:
        type: string
        enum:
          - scanning
      required: true
      description: >-
        The data domain of the report. The only supported value is `scanning`
      example: scanning

  schemas:
    ReportSchedule:
      type: object
      description: >-
        Schedule and configuration definition for a report generation
      required:
        - id
        - name
        - configuration
        - schedule
        - format
        - enabled
        - notificationChannelIds
      properties:
        id:
          type: string
          readOnly: true
          description: >-
            Unique opaque identifier of the report generation schedule.
          example: schedule-1hDkklCWc5UtuFhwCaZkbFNY5ZV
        name:
          type: string
          description: >-
            The title for the generated reports.
          example: Weekly vulnerability report
        description:
          type: string
          description: >-
            A human-readable description for the report content.
          example: |
            Weekly report for package vulnerabilities fount in the Production environment.
            Required for compliance needs.
        reportType:
          type: string
          description: >-
            The kind of report to generate
          enum:
            - vulnerabilities
            - policies
          example: vulnerabilities
        configuration:
          $ref: "#/components/schemas/ReportConfig"
        schedule:
          type: string
          pattern: "^[0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+ [0-9*/,-]+$"
          description: >-
            A cron-like expression representing the generation frequency of the reports.
          example: "0 9 * * 1"
        enabled:
          type: boolean
          description: >-
            Whether the report generation is active or not
          example: true
        notificationChannels:
          type: array
          description: >-
            Notification channels where to notify the generation of a new report along with the chosen report format
          items:
            type: object
            properties:
              notificationChannelId:
                type: integer
                description: >-
                  ID of notification channel where the generation of new reports is notified
                example: 12456
              format:
                type: string
                enum:
                  - csv
                  - json
                  - pdf
                description: >-
                  Format of the generated report
                example: csv
        status:
          type: object
          readOnly: true
          description: >-
            Schedule, start and completion timestamps for the latest report
          properties:
            lastScheduledAt:
              type: integer
              readOnly: true
              nullable: true
              description: >-
                The timestamp when a new generation of the scheduled report was last queued
              example: 1602674500
            lastStartedAt:
              type: integer
              readOnly: true
              nullable: true
              description: >-
                The timestamp when the generation of the scheduled report started the last time
              example: 1602674521
            lastCompletedAt:
              type: integer
              readOnly: true
              nullable: true
              description: >-
                The timestamp when the generation of the scheduled report completed the last time
              example: 1602674554
        createdAt:
          type: integer
          readOnly: true
          description: >-
            The timestamp when the schedule was defined the first time
          example: 1602672997
        updatedAt:
          type: integer
          readOnly: true
          description: >-
            The timestamp when the schedule was last updated
          example: 1602673124

    ReportConfig:
      type: object
      description: >-
        Configuration of a report generation
      required:
        - scope
        - columns
        - sorting
      properties:
        scope:
          type: object
          description: >-
            Filter the results based on the given scope
          properties:
            imageId:
              type: string
              nullable: true
              description: restrict the report generation on the given image ID
              example: sha256:b6fa739cedf5ea12a620a439402b6004d057da800f91c7524b5086a5e4749c9f
            runtimeEnabled:
              type: boolean
              description: whether the report should be filtered using a runtime scope
              example: true
            runtimeScope:
              type: string
              nullable: true
              description: An AND-composed string of predicates that restrict the scope of the generated report
            registry:
              type: string
              nullable: true
              description: Docker registry
              example: docker.io
            repository:
              type: string
              nullable: true
              description: Docker image repository
              example: debian
            tag:
              type: string
              nullable: true
              description: Docker image tag
              example: stable
        queryFilters:
          type: object
          additionalProperties:
            type: object
            properties:
              value:
                oneOf:
                  - type: string
                  - type: number
                  - type: boolean
                  - type: array
                    items:
                      type: string
                description: Filter value
              comparision:
                type: string
                nullable: true
                enum:
                  - "<"
                  - "<="
                  - "="
                  - ">="
                  - ">"
                description: Comparison operator to be applied with the chosen filter value
          description: >-
            Set of additional filter conditions on the generated reports.
            Filters are defined as map with filter names as key.
          example:
            vulnType:
              value: os
            fixAvailable:
              value: false
            severity:
              value: high
              comparison: ">="
        columns:
          type: array
          items:
            type: string
          description: >-
            The columns to be included in the generated report, in the order desired
          example:
            - vulnId
            - severity
            - package
        sorting:
          type: array
          description: Sorting criteria
          items:
            type: object
            required:
              - column
              - sortOrder
            properties:
              column:
                type: string
                description: >-
                  The column identifier chosen for sorting
                example: vulnId
              sortOrder:
                type: string
                enum:
                  - asc
                  - desc
                description: >-
                  The sorting order (ascending or descending) for the given column
                example: asc

    ReportingError:
      type: string
