openapi: 3.0.0
info:
  title: Compliance Secure Internal API
  description: API for Compliance service
  version: "v1"
paths:

components:
  schemas:
    controlDescription:
      type: object
      properties:
        standard:
          type: string
          example: PCI_3.2
        controlId:
          type: string
          example: 2.2.1.a
        description:
          type: string
          example: "Long form detailed description of the control"

    complianceReport:
      type: object
      properties:
        pass:
          type: number
          format: integer
          description: "Total number of passing controls for the entire compliance report"
          example: 30
        fail:
          type: number
          format: integer
          description: "Total number of failing controls for the entire compliance report"
          example: 20
        warn:
          type: number
          format: integer
          description: "Total number of controls in warn state for the entire compliance report"
          example: 7
        unchecked:
          type: number
          format: integer
          description: "Total number of controls not checked by Sysdig for the entire compliance report"
          example: 20
        checkedTotal:
          type: number
          format: integer
          description: "Total number of controls checked by Sysdig for the entire compliance report"
          example: 57
        families:
          type: array
          items:
            $ref: "#/components/schemas/family"
        bulkFails:
          type: array
          items:
            $ref: "#/components/schemas/bulkFail"

    family:
      type: object
      properties:
        pass:
          type: number
          format: integer
          description: "Total number of passing controls for the compliance family"
          example: 7
        total:
          type: number
          format: integer
          description: "Total number of controls for the compliance family"
          example: 10
        name:
          type: string
          description: "The name / heading of the given compliance family under a compliance section"
          example: "Do not use vendor-supplied defaults for system passwords and other security parameters"
        controls:
          type: array
          items:
            $ref: "#/components/schemas/control"

    control:
      type: object
      properties:
        name:
          type: string
          description: "Name of a single compliance control per standard"
          example: "One function per server isolation"
        id:
          type: string
          description: "The control id / number of the given control"
          example: "2.2.1.a"
        status:
          type: string
          enum:
            - PASS
            - FAIL
            - WARN
          example: PASS
        rationale:
          type: string
          description: "The explanation of what the checks are for a given control from Sysdig POV. This will be empty when detail=false"
          example: "Sysdig has falco policies that can be enabled to detect a particular scenario"
        description:
          type: string
          description: "The long form detailed description of a given control. This will be empty when detail=false"
          example: "Long form decsription"
        remediations:
          type: array
          items:
            $ref: "#/components/schemas/linkDetail"
        proofs:
          type: array
          items:
            $ref: "#/components/schemas/linkDetail"

    linkDetail:
      type: object
      properties:
        url:
          type: string
          description: "The full url to view the proof / remediation action for a given control"
          example: "https://secure.sysdig.com/#/policies?tags=PCI_3.2"
        text:
          type: string
          description: "The link text that is to be displayed for a proof/remediation url"
          example: "Enable k8s auditing"
        description:
          type: string
          description: "The description of what the link / activity is"
          example: "Schedule a CIS Benchmark to run on your infrastructure"

    bulkFail:
      type: object
      properties:
        action:
          type: string
          description: "The short action text for the type of remediation recommended"
          example: "Enable Falco Policy"
        controls:
          type: array
          items:
            $ref: "#/components/schemas/simpleControl"

    simpleControl:
      type: object
      properties:
        name:
          type: string
          description: "Name of the control"
          example: "Enable only necessary services, protocols and daemons."
        id:
          type: string
          description: "Control id / number"
          example: "2.2.1.a"
        status:
          type: string
          enum:
            - PASS
            - FAIL
            - WARN
          example: FAIL

  responses:
    badRequest:
      description: The given request is invalid.
    notFound:
      description: The compliance info could not be found.
    unauthorized:
      description: Invalid or missing auth token.
    forbidden:
      description: Forbidden access to view Compliance.
    serviceUnavailable:
      description: Service is unavailable.

