name: Swagger Validator

on: [ pull_request, push ]

jobs:
  swagger-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: install required tools
        run: npm install speccy -g
          npx speccy resolve A/api.yml -o original-spec.yaml

      - name: run the checkout action
        uses: actions/checkout@v2

      - name: run the git diff action
        uses: technote-space/get-diff-action@v4.1.1
        with:
          PATTERNS: docs/**/*.yaml
          SET_ENV_NAME: GIT_DIFF_CONTENT

      - name: validate oas definition
        # Check only if there are differences in docs/* code
        if: ${{ env.GIT_DIFF_CONTENT }}
        run: |
          npx speccy lint ${{ env.GIT_DIFF_CONTENT }}
#          npx speccy resolve A/api.yml -o original-spec.yaml
#          npx speccy resolve B/api.yml -o modified-spec.yaml
