name: Sysdig - Build, scan and push Docker Image

on: [ pull_request, push ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # with:
      #   fetch-depth: 0

    - name: Config git core.quotePath
      run: |
        # If you don't do this, the get-diff-action won't be able to
        # notice files that contain non-ascii characters.
        # I.e.
        #
        #    ▶ git status
        #    Changes not staged for commit:
        #    ...
        #   modified:   "files/en-us/glossary/b\303\251zier_curve/index.html"
        #
        # But after you set `core.quotePath` you get:
        #
        #    ▶ git status
        #    Changes not staged for commit:
        #    ...
        #   modified:   "files/en-us/glossary/bézier_curve/index.html"
        #
        # Now, this gets used by the `git diff ...` inside get-diff-action.
        git config --global core.quotePath false

    - uses: technote-space/get-diff-action@v4.1.1
      id: git_diff_content
      with:
        PATTERNS: src/**
        SET_ENV_NAME: GIT_DIFF_CONTENT
        FORMAT: json
    - run: echo '${{ env.GIT_DIFF_CONTENT }}' | jq .

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sysdiglabs/dummy-vuln-app:latest
      if: env.GIT_DIFF_CONTENT

    # - name: Sysdig Secure Inline Scan
    #   id: scan
    #   uses: sysdiglabs/scan-action@v3
    #   with:
    #     run-as-user: root
    #     sysdig-secure-url: https://us2.app.sysdig.com
    #     # Tag of the image to analyse
    #     image-tag: "sysdiglabs/dummy-vuln-app:latest"
    #     # API token for Sysdig Scanning auth
    #     sysdig-secure-token: ${{ secrets.KUBELAB_SECURE_API_TOKEN }}
    #     dockerfile-path: ./Dockerfile
    #     input-type: docker-daemon
    #     ignore-failed-scan: true

    # - uses: github/codeql-action/upload-sarif@v1
    #   if: always()
    #   with:
    #     sarif_file: ${{ steps.scan.outputs.sarifReport }}
